version: "3.8"
services:
  db:
    image: postgres:16
    container_name: pg-football
    environment:
      POSTGRES_DB: ogcn
      POSTGRES_USER: ogcn
      POSTGRES_PASSWORD: ogcn
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ogcn -d ogcn"]
      interval: 5s
      timeout: 3s
      retries: 10
volumes:
  pgdata: